- submissions/krishi_mitra.md
Dhananjay Chitale
- @DChitale  
---
---
This project focuses on bridging the gap between farmers and government schemes. It aims to make valuable information accessible to farmers through a user-friendly platform, enabling them to make better decisions for their livelihoods.
> Krishi-Mitra : Simplifying Access to Government Benefits for Every Farmer

- submissions/algomorph.md
**Shashank**
- [@shashankaz](https://github.com/shashankaz)
---
---
Nothing additional at this moment. Excited to be part of this hackathon!
> Add Algomorph submission to the hackathon repo

- submissions/unique-username-function.md
> submission: Appwrite-Unique-Username-Function

- submissions/kitchen_pal.md
> add Kitchenpal project

- submissions/scrummie-poker.md
Pijus Kamandulis
- @pikami 
---
---
Working with Appwrite was an exciting experience, especially since it was my first time using a backend-as-a-service platform. It provided me with all the tools I needed to make Scrummie-Poker come to life, and I thoroughly enjoyed the process.
> Added scrummie-poker submission

- submissions/event_planner.md
Avradeep Nayak
https://github.com/Zedoman
- [ X ] Yes
---
---
> event_planner.md

- submissions/MedConnect.md
Amarnath Rao @Amarnath-Rao 
* @Amarnath-Rao 
---
---
> MedConnect Submission For AppWrite Hackathon

- submissions/QuickShare.md
Luck Sharma
- [@mayank0274](https://github.com/mayank0274)
---
---
No
> hackathon submission : QuickShare

- submissions/careplus.md
Abhinab Das
- @abhi9ab 
---
---
> Careplus submission for AppWrite Hackathon

- submissions/EduMeet_Web
- Omprakash Chauhan
-  @omprakash2929 
---
---
> Add this repo to hackathon-submissions EduMeet_Web

- submissions/Patronus_Appwrite_hack_submission.md
- [@Vasu1712](https://github.com/Vasu1712)
Patronus is your personalized web assistant designed to scour the internet for the cheapest flight tickets matching your query, saving you valuable time from hopping between different operator websites.
1. **Authentication**: Securely log in to access the intuitive calendar-based UI.
2. **Setup Your Journey**:
- Select travel dates via our interactive calendar.
- Choose your airports.
- Specify the number of passengers.
3. **Request Flight Tickets**: With your preferences set, simply submit your request.
4. **Patronus at Work**: Receive the cheapest available flight tickets directly in your mailbox.
This project was born out of personal frustration - the tedious process of sifting through numerous flight options, wasting hours in search of the …
> Patronus- Appwrite Hackathon'24 Submission by Vasu1712

- submissions/React-Appwrite-RealTime-Chat.md
**Akshay Uttam Chame**
- @akshayram1  
_This is a mandatory step for all participants to be considered eligible for judging_  
---
By submitting this PR, you agree to follow our Rules and Code of Conduct.  
---
> Hackathon Submission: Real-Time Chat App Demo | React JS & Appwrite Hackathon Project

- submissions/weebhook.md
Kenneth Bass
- @dishwasher-detergent
---
---
No :)
> Weebhook.md

- submissions/launchbase.md
Aditya Aggarwal
- @aditya000099 
- [ x] Yes
---
---
> Add Launch Base submission to the appwrite hackathon

- submissions/Browser Power Tools
Lohit Nimbagal
@LohitNimbagal
---
---
> Add Browser Power Tools to the Hackathon Repo

- submissions/HealthPlus.md
Aditya Srivastava
- [@AdityaSrivastava185](https://github.com/AdityaSrivastava185)
---
---
No
> HealthPlus Hackathon Project Submission

- submissions/devx.md
Ankit Kumar
@ankit-0369 
---
---
> project devx added

- submissions/attendify.md
Sreejit Sengupta
@atulya-srivastava
@capsule11 
@Sreejit-Sengupto 
---
---
No thankyou, it was a great learning month while building for this hackathon,
> Submission attendify

- submissions/rroist.md
Shubham Parmar
- @Dey11 
- @KIWILmao 
- @Krish-Gupta07
---
---
We had a blast making this project - hope y'all like it. Thanks for giving us this space to showcase our ideas.
> Rroist (a form builder website with a CLI) - project submission

- submissions/eventManagement.md
Asmit Kumar Rai
@asmit27rai 
---
---
> Appwrite Submission

- submissions/aChief.md
Florian Herzler
- @floherzler
---
---
Hope to see cool projects that leverage Appwrite's capabilities!
I know I didn't get to do all that I wanted due to time reasons :)
> submission: aChief

- submissions/heart-bridge.md
Prince Onukwili
- [@onukwilip](https://github.com/onukwilip)
- [@python-fuse](https://github.com/python-fuse)
- [@maxe01](https://github.com/maxe01)
---
---
> Submission of my Appwrite hackathon project - Heart Bridge

- submissions/quick-vocab.md
Olugbemi Tolulope
@Opedepodepes-Olugbemi 
---
---
> Quick-Vocab

- submissions/entrepreneurs-hub-web-app.md
Eliezer Joel Kaggulire
@eliezerjoel
---
> Enthub by @eliezerjoel

- submissions/ScholarLift.md
Asmit Barua
@asmb123 
@prathmesh703
@Lokeshranjan8
@chiragmalik2612
---
---
> appwrite submission : ScholarLift

- submissions/app-comment.md
> add app-comment

- submissions/means-HF
Aditya Kumar
- @gitadityakumar 
---
---
NO
> add means-HF appwrite hackathon submission

- submissions/FeedbackSO
Arnab Chatterjee
---
---
The hackathon actually provided me a sprint mindset to complete my app idea in just 14 days.
> Created FeedbackSO

- submissions/FashionSathi.md
Ashish Singh Nagvanshi
- @SavantCode
- @nagvanshi9275
- @bhavya123gupta
- @RishiAnand108
---
---
> Add FashionSathi submission to the hackathon repo

- submissions/SoundStake.md
Aditya Mahamuni
- [@Robinaditya1045](https://github.com/Robinaditya1045)
- [@digvijay-555](https://github.com/digvijay-555)
- [@vishal18713](https://github.com/vishal18713)
- [@vedantJadhav0017](https://github.com/VedantJadhav0017)
---
---
Thank for such a great event. Had fun building on **Appwrite**
> Add SoundStake submission to hackathon repo

- submissions/devpath.md
DevPath
Dipanshu Rawat
Jaydeep Rawat
- @dipanshurdev 
- @jaydeeprawat17
---
---
> add: project devpath

- submissions/CodeSnippetVault.md
Aishwary Gupta
@Aishwary2004Gupta 
-  Yes ✅
---
---
> Code-Snippet-Vault submission to the Hacktoberfest repo

- submissions/Suraksha.md
Ritvija Pachori
- **Ritvija Pachori** @ritvijapachori - Android Developer
- **Ayush Deshmukh** @Deshmukh-Ayush - Web & App Developer
- **Pragya Hurmade** @Pragyaa3 - Web Developer
- **Satyam Sharma** @satyamsharma17 - Android Developer
---
---
> Add Suraksha to the Submission folder

- submissions/pipelineui.md
Riccardo Perra
@riccardoperra
---
---
With this project I'll partecipate also in [SolidHack 2024](https://hack.solidjs.com/).
I'm linking here the `appwrite` branch that will not be updated until the end of the hackathon.
Also the application has been hosted in `railway` with a custom environment in order to separate the two submissions. Currently I made the project public in order to check the deploy status of this environment
Appwrite deployments: https://github.com/riccardoperra/pipelineui/deployments/appwrite
Appwrite public deployment: https://railway.app/project/8e131c67-73c1-4ab6-9fa4-31dfa6c9000e -> Go to appwrite environment
Deploy file: https://github.com/riccardoperra/pipelineui/blob/8ba00ed19abf7d1e5884aa …
> Add PipelineUI

- submissions/joblier.md
Fasakin Henry
- @fasakinhenry 
- @fisayo-dev
The project should be tested thoroughly as I was not able to cover much in the 3 mins demo for the hackathon
Joblier
**AI-powered Job Search Platform**
We created a platform that simplifies the process of Finding jobs with the help of AI.
The app has two category of users:
- Recruiters
- Job Seekers
The Recruiters have their portal which allows them to post jobs with requirement and see job seekers profile with their stats and all garnered through their portal. They can also see top professionals in the fields and initiate conversations with them.
Job seekers platform has been built and has many of the following features that makes users get the job by helping them build …
> Joblier App

- spellsentry.md
Madhav Singh
- @madhav-relish 
- @sajdakabir 
---
---
> Add submission for SpellSentry Project

- submissions/Trackpot.md
Seemant Shekhar
- @seemantshekhar43 
---
> Add Trackpot submission to hackathon repo

- submissions/Orbit.md
Rami Maalouf
@psycho-baller 
---
---
> Orbit submission

- submissions/wisdoma.md
Om Gate
[@OMGATE23](https://github.com/OMGATE23)
---
---
none
> Wisdoma: Your Note-Taking App, Visualizing Your Notes through Knowledge Graphs

- submissions/SnapStudio.md
Rajeev Sharma
- @rajeev033 
- @eik-1
-->
---
---
> add SnapStudio.md hackathon submission

- submissions/adventure-log.md
> appwrite project submission
